// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// UserGetReader is a Reader for the UserGet structure.
type UserGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUserGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewUserGetNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserGetOK creates a UserGetOK with default headers values
func NewUserGetOK() *UserGetOK {
	return &UserGetOK{}
}

/*UserGetOK handles this case with default header values.

User
*/
type UserGetOK struct {
	Payload UserGetOKBody
}

func (o *UserGetOK) Error() string {
	return fmt.Sprintf("[GET /users/{username}][%d] userGetOK  %+v", 200, o.Payload)
}

func (o *UserGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserGetNotFound creates a UserGetNotFound with default headers values
func NewUserGetNotFound() *UserGetNotFound {
	return &UserGetNotFound{}
}

/*UserGetNotFound handles this case with default header values.

APINotFound is a not found empty response
*/
type UserGetNotFound struct {
}

func (o *UserGetNotFound) Error() string {
	return fmt.Sprintf("[GET /users/{username}][%d] userGetNotFound ", 404)
}

func (o *UserGetNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*UserGetOKBody User represents a user
swagger:model UserGetOKBody
*/
type UserGetOKBody struct {

	// URL to the user's avatar
	// Required: true
	AvatarURL *string `json:"avatar_url"`

	// email
	// Required: true
	// Format: email
	Email *strfmt.Email `json:"email"`

	// the user's full name
	// Required: true
	FullName *string `json:"full_name"`

	// the user's id
	// Required: true
	ID *int64 `json:"id"`

	// User locale
	// Required: true
	Language *string `json:"language"`

	// the user's username
	// Required: true
	UserName *string `json:"login"`
}

// Validate validates this user get o k body
func (o *UserGetOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAvatarURL(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateFullName(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLanguage(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUserName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UserGetOKBody) validateAvatarURL(formats strfmt.Registry) error {

	if err := validate.Required("userGetOK"+"."+"avatar_url", "body", o.AvatarURL); err != nil {
		return err
	}

	return nil
}

func (o *UserGetOKBody) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("userGetOK"+"."+"email", "body", o.Email); err != nil {
		return err
	}

	if err := validate.FormatOf("userGetOK"+"."+"email", "body", "email", o.Email.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *UserGetOKBody) validateFullName(formats strfmt.Registry) error {

	if err := validate.Required("userGetOK"+"."+"full_name", "body", o.FullName); err != nil {
		return err
	}

	return nil
}

func (o *UserGetOKBody) validateID(formats strfmt.Registry) error {

	if err := validate.Required("userGetOK"+"."+"id", "body", o.ID); err != nil {
		return err
	}

	return nil
}

func (o *UserGetOKBody) validateLanguage(formats strfmt.Registry) error {

	if err := validate.Required("userGetOK"+"."+"language", "body", o.Language); err != nil {
		return err
	}

	return nil
}

func (o *UserGetOKBody) validateUserName(formats strfmt.Registry) error {

	if err := validate.Required("userGetOK"+"."+"login", "body", o.UserName); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *UserGetOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *UserGetOKBody) UnmarshalBinary(b []byte) error {
	var res UserGetOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
