// Code generated by go-swagger; DO NOT EDIT.

package issue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new issue API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for issue API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
IssueAddLabel adds a label to an issue
*/
func (a *Client) IssueAddLabel(params *IssueAddLabelParams, authInfo runtime.ClientAuthInfoWriter) (*IssueAddLabelOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueAddLabelParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueAddLabel",
		Method:             "POST",
		PathPattern:        "/repos/{owner}/{repo}/issues/{index}/labels",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueAddLabelReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueAddLabelOK), nil

}

/*
IssueAddTime adds a tracked time to a issue
*/
func (a *Client) IssueAddTime(params *IssueAddTimeParams, authInfo runtime.ClientAuthInfoWriter) (*IssueAddTimeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueAddTimeParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueAddTime",
		Method:             "POST",
		PathPattern:        "/repos/{owner}/{repo}/issues/{id}/times",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueAddTimeReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueAddTimeOK), nil

}

/*
IssueClearLabels removes all labels from an issue
*/
func (a *Client) IssueClearLabels(params *IssueClearLabelsParams, authInfo runtime.ClientAuthInfoWriter) (*IssueClearLabelsNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueClearLabelsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueClearLabels",
		Method:             "DELETE",
		PathPattern:        "/repos/{owner}/{repo}/issues/{index}/labels",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueClearLabelsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueClearLabelsNoContent), nil

}

/*
IssueCreateComment adds a comment to an issue
*/
func (a *Client) IssueCreateComment(params *IssueCreateCommentParams, authInfo runtime.ClientAuthInfoWriter) (*IssueCreateCommentCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueCreateCommentParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueCreateComment",
		Method:             "POST",
		PathPattern:        "/repos/{owner}/{repo}/issues/{index}/comments",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueCreateCommentReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueCreateCommentCreated), nil

}

/*
IssueCreateIssue creates an issue
*/
func (a *Client) IssueCreateIssue(params *IssueCreateIssueParams, authInfo runtime.ClientAuthInfoWriter) (*IssueCreateIssueCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueCreateIssueParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueCreateIssue",
		Method:             "POST",
		PathPattern:        "/repos/{owner}/{repo}/issues",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueCreateIssueReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueCreateIssueCreated), nil

}

/*
IssueCreateLabel creates a label
*/
func (a *Client) IssueCreateLabel(params *IssueCreateLabelParams, authInfo runtime.ClientAuthInfoWriter) (*IssueCreateLabelCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueCreateLabelParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueCreateLabel",
		Method:             "POST",
		PathPattern:        "/repos/{owner}/{repo}/labels",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueCreateLabelReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueCreateLabelCreated), nil

}

/*
IssueCreateMilestone creates a milestone
*/
func (a *Client) IssueCreateMilestone(params *IssueCreateMilestoneParams, authInfo runtime.ClientAuthInfoWriter) (*IssueCreateMilestoneCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueCreateMilestoneParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueCreateMilestone",
		Method:             "POST",
		PathPattern:        "/repos/{owner}/{repo}/milestones",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueCreateMilestoneReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueCreateMilestoneCreated), nil

}

/*
IssueDeleteComment deletes a comment
*/
func (a *Client) IssueDeleteComment(params *IssueDeleteCommentParams, authInfo runtime.ClientAuthInfoWriter) (*IssueDeleteCommentNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueDeleteCommentParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueDeleteComment",
		Method:             "DELETE",
		PathPattern:        "/repos/{owner}/{repo}/issues/comments/{id}",
		ProducesMediaTypes: []string{"application/json", "text/html"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueDeleteCommentReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueDeleteCommentNoContent), nil

}

/*
IssueDeleteCommentDeprecated deletes a comment
*/
func (a *Client) IssueDeleteCommentDeprecated(params *IssueDeleteCommentDeprecatedParams, authInfo runtime.ClientAuthInfoWriter) (*IssueDeleteCommentDeprecatedNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueDeleteCommentDeprecatedParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueDeleteCommentDeprecated",
		Method:             "DELETE",
		PathPattern:        "/repos/{owner}/{repo}/issues/{index}/comments/{id}",
		ProducesMediaTypes: []string{"application/json", "text/html"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueDeleteCommentDeprecatedReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueDeleteCommentDeprecatedNoContent), nil

}

/*
IssueDeleteLabel deletes a label
*/
func (a *Client) IssueDeleteLabel(params *IssueDeleteLabelParams, authInfo runtime.ClientAuthInfoWriter) (*IssueDeleteLabelNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueDeleteLabelParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueDeleteLabel",
		Method:             "DELETE",
		PathPattern:        "/repos/{owner}/{repo}/labels/{id}",
		ProducesMediaTypes: []string{"application/json", "text/html"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueDeleteLabelReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueDeleteLabelNoContent), nil

}

/*
IssueDeleteMilestone deletes a milestone
*/
func (a *Client) IssueDeleteMilestone(params *IssueDeleteMilestoneParams, authInfo runtime.ClientAuthInfoWriter) (*IssueDeleteMilestoneNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueDeleteMilestoneParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueDeleteMilestone",
		Method:             "DELETE",
		PathPattern:        "/repos/{owner}/{repo}/milestones/{id}",
		ProducesMediaTypes: []string{"application/json", "text/html"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueDeleteMilestoneReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueDeleteMilestoneNoContent), nil

}

/*
IssueEditComment edits a comment
*/
func (a *Client) IssueEditComment(params *IssueEditCommentParams, authInfo runtime.ClientAuthInfoWriter) (*IssueEditCommentOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueEditCommentParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueEditComment",
		Method:             "PATCH",
		PathPattern:        "/repos/{owner}/{repo}/issues/comments/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueEditCommentReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueEditCommentOK), nil

}

/*
IssueEditCommentDeprecated edits a comment
*/
func (a *Client) IssueEditCommentDeprecated(params *IssueEditCommentDeprecatedParams, authInfo runtime.ClientAuthInfoWriter) (*IssueEditCommentDeprecatedOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueEditCommentDeprecatedParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueEditCommentDeprecated",
		Method:             "PATCH",
		PathPattern:        "/repos/{owner}/{repo}/issues/{index}/comments/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueEditCommentDeprecatedReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueEditCommentDeprecatedOK), nil

}

/*
IssueEditIssue edits an issue
*/
func (a *Client) IssueEditIssue(params *IssueEditIssueParams, authInfo runtime.ClientAuthInfoWriter) (*IssueEditIssueCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueEditIssueParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueEditIssue",
		Method:             "PATCH",
		PathPattern:        "/repos/{owner}/{repo}/issues/{index}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueEditIssueReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueEditIssueCreated), nil

}

/*
IssueEditLabel updates a label
*/
func (a *Client) IssueEditLabel(params *IssueEditLabelParams, authInfo runtime.ClientAuthInfoWriter) (*IssueEditLabelOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueEditLabelParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueEditLabel",
		Method:             "PATCH",
		PathPattern:        "/repos/{owner}/{repo}/labels/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueEditLabelReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueEditLabelOK), nil

}

/*
IssueEditMilestone updates a milestone
*/
func (a *Client) IssueEditMilestone(params *IssueEditMilestoneParams, authInfo runtime.ClientAuthInfoWriter) (*IssueEditMilestoneOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueEditMilestoneParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueEditMilestone",
		Method:             "PATCH",
		PathPattern:        "/repos/{owner}/{repo}/milestones/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueEditMilestoneReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueEditMilestoneOK), nil

}

/*
IssueGetComments lists all comments on an issue
*/
func (a *Client) IssueGetComments(params *IssueGetCommentsParams, authInfo runtime.ClientAuthInfoWriter) (*IssueGetCommentsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueGetCommentsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueGetComments",
		Method:             "GET",
		PathPattern:        "/repos/{owner}/{repo}/issues/{index}/comments",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueGetCommentsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueGetCommentsOK), nil

}

/*
IssueGetIssue gets an issue
*/
func (a *Client) IssueGetIssue(params *IssueGetIssueParams, authInfo runtime.ClientAuthInfoWriter) (*IssueGetIssueOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueGetIssueParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueGetIssue",
		Method:             "GET",
		PathPattern:        "/repos/{owner}/{repo}/issues/{index}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueGetIssueReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueGetIssueOK), nil

}

/*
IssueGetLabel gets a single label
*/
func (a *Client) IssueGetLabel(params *IssueGetLabelParams, authInfo runtime.ClientAuthInfoWriter) (*IssueGetLabelOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueGetLabelParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueGetLabel",
		Method:             "GET",
		PathPattern:        "/repos/{owner}/{repo}/labels/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueGetLabelReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueGetLabelOK), nil

}

/*
IssueGetLabels gets an issue s labels
*/
func (a *Client) IssueGetLabels(params *IssueGetLabelsParams, authInfo runtime.ClientAuthInfoWriter) (*IssueGetLabelsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueGetLabelsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueGetLabels",
		Method:             "GET",
		PathPattern:        "/repos/{owner}/{repo}/issues/{index}/labels",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueGetLabelsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueGetLabelsOK), nil

}

/*
IssueGetMilestone gets a milestone
*/
func (a *Client) IssueGetMilestone(params *IssueGetMilestoneParams, authInfo runtime.ClientAuthInfoWriter) (*IssueGetMilestoneOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueGetMilestoneParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueGetMilestone",
		Method:             "GET",
		PathPattern:        "/repos/{owner}/{repo}/milestones/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueGetMilestoneReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueGetMilestoneOK), nil

}

/*
IssueGetMilestonesList gets all of a repository s milestones
*/
func (a *Client) IssueGetMilestonesList(params *IssueGetMilestonesListParams, authInfo runtime.ClientAuthInfoWriter) (*IssueGetMilestonesListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueGetMilestonesListParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueGetMilestonesList",
		Method:             "GET",
		PathPattern:        "/repos/{owner}/{repo}/milestones",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueGetMilestonesListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueGetMilestonesListOK), nil

}

/*
IssueGetRepoComments lists all comments in a repository
*/
func (a *Client) IssueGetRepoComments(params *IssueGetRepoCommentsParams, authInfo runtime.ClientAuthInfoWriter) (*IssueGetRepoCommentsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueGetRepoCommentsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueGetRepoComments",
		Method:             "GET",
		PathPattern:        "/repos/{owner}/{repo}/issues/comments",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueGetRepoCommentsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueGetRepoCommentsOK), nil

}

/*
IssueListIssues lists a repository s issues
*/
func (a *Client) IssueListIssues(params *IssueListIssuesParams, authInfo runtime.ClientAuthInfoWriter) (*IssueListIssuesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueListIssuesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueListIssues",
		Method:             "GET",
		PathPattern:        "/repos/{owner}/{repo}/issues",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueListIssuesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueListIssuesOK), nil

}

/*
IssueListLabels gets all of a repository s labels
*/
func (a *Client) IssueListLabels(params *IssueListLabelsParams, authInfo runtime.ClientAuthInfoWriter) (*IssueListLabelsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueListLabelsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueListLabels",
		Method:             "GET",
		PathPattern:        "/repos/{owner}/{repo}/labels",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueListLabelsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueListLabelsOK), nil

}

/*
IssueRemoveLabel removes a label from an issue
*/
func (a *Client) IssueRemoveLabel(params *IssueRemoveLabelParams, authInfo runtime.ClientAuthInfoWriter) (*IssueRemoveLabelNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueRemoveLabelParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueRemoveLabel",
		Method:             "DELETE",
		PathPattern:        "/repos/{owner}/{repo}/issues/{index}/labels/{id}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueRemoveLabelReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueRemoveLabelNoContent), nil

}

/*
IssueReplaceLabels replaces an issue s labels
*/
func (a *Client) IssueReplaceLabels(params *IssueReplaceLabelsParams, authInfo runtime.ClientAuthInfoWriter) (*IssueReplaceLabelsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueReplaceLabelsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueReplaceLabels",
		Method:             "PUT",
		PathPattern:        "/repos/{owner}/{repo}/issues/{index}/labels",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueReplaceLabelsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueReplaceLabelsOK), nil

}

/*
IssueTrackedTimes lists an issue s tracked times
*/
func (a *Client) IssueTrackedTimes(params *IssueTrackedTimesParams, authInfo runtime.ClientAuthInfoWriter) (*IssueTrackedTimesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewIssueTrackedTimesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "issueTrackedTimes",
		Method:             "GET",
		PathPattern:        "/repos/{owner}/{repo}/issues/{id}/times",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json", "text/plain"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &IssueTrackedTimesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*IssueTrackedTimesOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
