// Code generated by go-swagger; DO NOT EDIT.

package issue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/sapk/go-swagger-client-gitea/models"
)

// IssueGetIssueReader is a Reader for the IssueGetIssue structure.
type IssueGetIssueReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IssueGetIssueReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewIssueGetIssueOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIssueGetIssueOK creates a IssueGetIssueOK with default headers values
func NewIssueGetIssueOK() *IssueGetIssueOK {
	return &IssueGetIssueOK{}
}

/*IssueGetIssueOK handles this case with default header values.

Issue
*/
type IssueGetIssueOK struct {
	Payload IssueGetIssueOKBody
}

func (o *IssueGetIssueOK) Error() string {
	return fmt.Sprintf("[GET /repos/{owner}/{repo}/issues/{index}][%d] issueGetIssueOK  %+v", 200, o.Payload)
}

func (o *IssueGetIssueOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*AssigneesItems0 User represents a user
swagger:model AssigneesItems0
*/
type AssigneesItems0 struct {

	// URL to the user's avatar
	AvatarURL string `json:"avatar_url,omitempty"`

	// email
	// Format: email
	Email strfmt.Email `json:"email,omitempty"`

	// the user's full name
	FullName string `json:"full_name,omitempty"`

	// the user's id
	ID int64 `json:"id,omitempty"`

	// User locale
	Language string `json:"language,omitempty"`

	// the user's username
	UserName string `json:"login,omitempty"`
}

// Validate validates this assignees items0
func (o *AssigneesItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *AssigneesItems0) validateEmail(formats strfmt.Registry) error {

	if swag.IsZero(o.Email) { // not required
		return nil
	}

	if err := validate.FormatOf("email", "body", "email", o.Email.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *AssigneesItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *AssigneesItems0) UnmarshalBinary(b []byte) error {
	var res AssigneesItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*IssueGetIssueOKBody Issue represents an issue in a repository
swagger:model IssueGetIssueOKBody
*/
type IssueGetIssueOKBody struct {

	// assignees
	// Required: true
	Assignees []*models.AssigneesItems0 `json:"assignees"`

	// body
	// Required: true
	Body *string `json:"body"`

	// closed
	// Required: true
	// Format: date-time
	Closed *strfmt.DateTime `json:"closed_at"`

	// comments
	// Required: true
	Comments *int64 `json:"comments"`

	// created
	// Required: true
	// Format: date-time
	Created *strfmt.DateTime `json:"created_at"`

	// deadline
	// Required: true
	// Format: date-time
	Deadline *strfmt.DateTime `json:"due_date"`

	// ID
	// Required: true
	ID *int64 `json:"id"`

	// index
	// Required: true
	Index *int64 `json:"number"`

	// labels
	// Required: true
	Labels []*models.LabelsItems0 `json:"labels"`

	// title
	// Required: true
	Title *string `json:"title"`

	// URL
	// Required: true
	URL *string `json:"url"`

	// updated
	// Required: true
	// Format: date-time
	Updated *strfmt.DateTime `json:"updated_at"`

	// assignee
	// Required: true
	Assignee *IssueGetIssueOKBodyAssignee `json:"assignee"`

	// milestone
	// Required: true
	Milestone *IssueGetIssueOKBodyMilestone `json:"milestone"`

	// pull request
	// Required: true
	PullRequest *IssueGetIssueOKBodyPullRequest `json:"pull_request"`

	// StateType issue state type
	// Required: true
	State *string `json:"state"`

	// user
	// Required: true
	User *IssueGetIssueOKBodyUser `json:"user"`
}

// Validate validates this issue get issue o k body
func (o *IssueGetIssueOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAssignees(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateBody(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateClosed(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateComments(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDeadline(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateIndex(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLabels(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTitle(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUpdated(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateAssignee(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMilestone(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePullRequest(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateState(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUser(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *IssueGetIssueOKBody) validateAssignees(formats strfmt.Registry) error {

	if err := validate.Required("issueGetIssueOK"+"."+"assignees", "body", o.Assignees); err != nil {
		return err
	}

	for i := 0; i < len(o.Assignees); i++ {
		if swag.IsZero(o.Assignees[i]) { // not required
			continue
		}

		if o.Assignees[i] != nil {
			if err := o.Assignees[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("issueGetIssueOK" + "." + "assignees" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *IssueGetIssueOKBody) validateBody(formats strfmt.Registry) error {

	if err := validate.Required("issueGetIssueOK"+"."+"body", "body", o.Body); err != nil {
		return err
	}

	return nil
}

func (o *IssueGetIssueOKBody) validateClosed(formats strfmt.Registry) error {

	if err := validate.Required("issueGetIssueOK"+"."+"closed_at", "body", o.Closed); err != nil {
		return err
	}

	if err := validate.FormatOf("issueGetIssueOK"+"."+"closed_at", "body", "date-time", o.Closed.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *IssueGetIssueOKBody) validateComments(formats strfmt.Registry) error {

	if err := validate.Required("issueGetIssueOK"+"."+"comments", "body", o.Comments); err != nil {
		return err
	}

	return nil
}

func (o *IssueGetIssueOKBody) validateCreated(formats strfmt.Registry) error {

	if err := validate.Required("issueGetIssueOK"+"."+"created_at", "body", o.Created); err != nil {
		return err
	}

	if err := validate.FormatOf("issueGetIssueOK"+"."+"created_at", "body", "date-time", o.Created.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *IssueGetIssueOKBody) validateDeadline(formats strfmt.Registry) error {

	if err := validate.Required("issueGetIssueOK"+"."+"due_date", "body", o.Deadline); err != nil {
		return err
	}

	if err := validate.FormatOf("issueGetIssueOK"+"."+"due_date", "body", "date-time", o.Deadline.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *IssueGetIssueOKBody) validateID(formats strfmt.Registry) error {

	if err := validate.Required("issueGetIssueOK"+"."+"id", "body", o.ID); err != nil {
		return err
	}

	return nil
}

func (o *IssueGetIssueOKBody) validateIndex(formats strfmt.Registry) error {

	if err := validate.Required("issueGetIssueOK"+"."+"number", "body", o.Index); err != nil {
		return err
	}

	return nil
}

func (o *IssueGetIssueOKBody) validateLabels(formats strfmt.Registry) error {

	if err := validate.Required("issueGetIssueOK"+"."+"labels", "body", o.Labels); err != nil {
		return err
	}

	for i := 0; i < len(o.Labels); i++ {
		if swag.IsZero(o.Labels[i]) { // not required
			continue
		}

		if o.Labels[i] != nil {
			if err := o.Labels[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("issueGetIssueOK" + "." + "labels" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *IssueGetIssueOKBody) validateTitle(formats strfmt.Registry) error {

	if err := validate.Required("issueGetIssueOK"+"."+"title", "body", o.Title); err != nil {
		return err
	}

	return nil
}

func (o *IssueGetIssueOKBody) validateURL(formats strfmt.Registry) error {

	if err := validate.Required("issueGetIssueOK"+"."+"url", "body", o.URL); err != nil {
		return err
	}

	return nil
}

func (o *IssueGetIssueOKBody) validateUpdated(formats strfmt.Registry) error {

	if err := validate.Required("issueGetIssueOK"+"."+"updated_at", "body", o.Updated); err != nil {
		return err
	}

	if err := validate.FormatOf("issueGetIssueOK"+"."+"updated_at", "body", "date-time", o.Updated.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *IssueGetIssueOKBody) validateAssignee(formats strfmt.Registry) error {

	if err := validate.Required("issueGetIssueOK"+"."+"assignee", "body", o.Assignee); err != nil {
		return err
	}

	if o.Assignee != nil {
		if err := o.Assignee.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("issueGetIssueOK" + "." + "assignee")
			}
			return err
		}
	}

	return nil
}

func (o *IssueGetIssueOKBody) validateMilestone(formats strfmt.Registry) error {

	if err := validate.Required("issueGetIssueOK"+"."+"milestone", "body", o.Milestone); err != nil {
		return err
	}

	if o.Milestone != nil {
		if err := o.Milestone.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("issueGetIssueOK" + "." + "milestone")
			}
			return err
		}
	}

	return nil
}

func (o *IssueGetIssueOKBody) validatePullRequest(formats strfmt.Registry) error {

	if err := validate.Required("issueGetIssueOK"+"."+"pull_request", "body", o.PullRequest); err != nil {
		return err
	}

	if o.PullRequest != nil {
		if err := o.PullRequest.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("issueGetIssueOK" + "." + "pull_request")
			}
			return err
		}
	}

	return nil
}

func (o *IssueGetIssueOKBody) validateState(formats strfmt.Registry) error {

	if err := validate.Required("issueGetIssueOK"+"."+"state", "body", o.State); err != nil {
		return err
	}

	return nil
}

func (o *IssueGetIssueOKBody) validateUser(formats strfmt.Registry) error {

	if err := validate.Required("issueGetIssueOK"+"."+"user", "body", o.User); err != nil {
		return err
	}

	if o.User != nil {
		if err := o.User.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("issueGetIssueOK" + "." + "user")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *IssueGetIssueOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *IssueGetIssueOKBody) UnmarshalBinary(b []byte) error {
	var res IssueGetIssueOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*IssueGetIssueOKBodyAssignee User represents a user
swagger:model IssueGetIssueOKBodyAssignee
*/
type IssueGetIssueOKBodyAssignee struct {

	// URL to the user's avatar
	AvatarURL string `json:"avatar_url,omitempty"`

	// email
	// Format: email
	Email strfmt.Email `json:"email,omitempty"`

	// the user's full name
	FullName string `json:"full_name,omitempty"`

	// the user's id
	ID int64 `json:"id,omitempty"`

	// User locale
	Language string `json:"language,omitempty"`

	// the user's username
	UserName string `json:"login,omitempty"`
}

// Validate validates this issue get issue o k body assignee
func (o *IssueGetIssueOKBodyAssignee) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *IssueGetIssueOKBodyAssignee) validateEmail(formats strfmt.Registry) error {

	if swag.IsZero(o.Email) { // not required
		return nil
	}

	if err := validate.FormatOf("issueGetIssueOK"+"."+"assignee"+"."+"email", "body", "email", o.Email.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *IssueGetIssueOKBodyAssignee) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *IssueGetIssueOKBodyAssignee) UnmarshalBinary(b []byte) error {
	var res IssueGetIssueOKBodyAssignee
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*IssueGetIssueOKBodyMilestone Milestone milestone is a collection of issues on one repository
swagger:model IssueGetIssueOKBodyMilestone
*/
type IssueGetIssueOKBodyMilestone struct {

	// closed
	// Format: date-time
	Closed strfmt.DateTime `json:"closed_at,omitempty"`

	// closed issues
	ClosedIssues int64 `json:"closed_issues,omitempty"`

	// deadline
	// Format: date-time
	Deadline strfmt.DateTime `json:"due_on,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// ID
	ID int64 `json:"id,omitempty"`

	// open issues
	OpenIssues int64 `json:"open_issues,omitempty"`

	// title
	Title string `json:"title,omitempty"`

	// StateType issue state type
	State string `json:"state,omitempty"`
}

// Validate validates this issue get issue o k body milestone
func (o *IssueGetIssueOKBodyMilestone) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateClosed(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDeadline(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *IssueGetIssueOKBodyMilestone) validateClosed(formats strfmt.Registry) error {

	if swag.IsZero(o.Closed) { // not required
		return nil
	}

	if err := validate.FormatOf("issueGetIssueOK"+"."+"milestone"+"."+"closed_at", "body", "date-time", o.Closed.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *IssueGetIssueOKBodyMilestone) validateDeadline(formats strfmt.Registry) error {

	if swag.IsZero(o.Deadline) { // not required
		return nil
	}

	if err := validate.FormatOf("issueGetIssueOK"+"."+"milestone"+"."+"due_on", "body", "date-time", o.Deadline.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *IssueGetIssueOKBodyMilestone) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *IssueGetIssueOKBodyMilestone) UnmarshalBinary(b []byte) error {
	var res IssueGetIssueOKBodyMilestone
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*IssueGetIssueOKBodyPullRequest PullRequestMeta PR info if an issue is a PR
swagger:model IssueGetIssueOKBodyPullRequest
*/
type IssueGetIssueOKBodyPullRequest struct {

	// has merged
	HasMerged bool `json:"merged,omitempty"`

	// merged
	// Format: date-time
	Merged strfmt.DateTime `json:"merged_at,omitempty"`
}

// Validate validates this issue get issue o k body pull request
func (o *IssueGetIssueOKBodyPullRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMerged(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *IssueGetIssueOKBodyPullRequest) validateMerged(formats strfmt.Registry) error {

	if swag.IsZero(o.Merged) { // not required
		return nil
	}

	if err := validate.FormatOf("issueGetIssueOK"+"."+"pull_request"+"."+"merged_at", "body", "date-time", o.Merged.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *IssueGetIssueOKBodyPullRequest) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *IssueGetIssueOKBodyPullRequest) UnmarshalBinary(b []byte) error {
	var res IssueGetIssueOKBodyPullRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*IssueGetIssueOKBodyUser User represents a user
swagger:model IssueGetIssueOKBodyUser
*/
type IssueGetIssueOKBodyUser struct {

	// URL to the user's avatar
	AvatarURL string `json:"avatar_url,omitempty"`

	// email
	// Format: email
	Email strfmt.Email `json:"email,omitempty"`

	// the user's full name
	FullName string `json:"full_name,omitempty"`

	// the user's id
	ID int64 `json:"id,omitempty"`

	// User locale
	Language string `json:"language,omitempty"`

	// the user's username
	UserName string `json:"login,omitempty"`
}

// Validate validates this issue get issue o k body user
func (o *IssueGetIssueOKBodyUser) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *IssueGetIssueOKBodyUser) validateEmail(formats strfmt.Registry) error {

	if swag.IsZero(o.Email) { // not required
		return nil
	}

	if err := validate.FormatOf("issueGetIssueOK"+"."+"user"+"."+"email", "body", "email", o.Email.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *IssueGetIssueOKBodyUser) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *IssueGetIssueOKBodyUser) UnmarshalBinary(b []byte) error {
	var res IssueGetIssueOKBodyUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*LabelsItems0 Label a label to an issue or a pr
swagger:model LabelsItems0
*/
type LabelsItems0 struct {

	// color
	Color string `json:"color,omitempty"`

	// ID
	ID int64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// URL
	URL string `json:"url,omitempty"`
}

// Validate validates this labels items0
func (o *LabelsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (o *LabelsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *LabelsItems0) UnmarshalBinary(b []byte) error {
	var res LabelsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
