// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRepoListStatusesParams creates a new RepoListStatusesParams object
// with the default values initialized.
func NewRepoListStatusesParams() *RepoListStatusesParams {
	var ()
	return &RepoListStatusesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRepoListStatusesParamsWithTimeout creates a new RepoListStatusesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRepoListStatusesParamsWithTimeout(timeout time.Duration) *RepoListStatusesParams {
	var ()
	return &RepoListStatusesParams{

		timeout: timeout,
	}
}

// NewRepoListStatusesParamsWithContext creates a new RepoListStatusesParams object
// with the default values initialized, and the ability to set a context for a request
func NewRepoListStatusesParamsWithContext(ctx context.Context) *RepoListStatusesParams {
	var ()
	return &RepoListStatusesParams{

		Context: ctx,
	}
}

// NewRepoListStatusesParamsWithHTTPClient creates a new RepoListStatusesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRepoListStatusesParamsWithHTTPClient(client *http.Client) *RepoListStatusesParams {
	var ()
	return &RepoListStatusesParams{
		HTTPClient: client,
	}
}

/*RepoListStatusesParams contains all the parameters to send to the API endpoint
for the repo list statuses operation typically these are written to a http.Request
*/
type RepoListStatusesParams struct {

	/*Owner
	  owner of the repo

	*/
	Owner string
	/*Repo
	  name of the repo

	*/
	Repo string
	/*Sha
	  sha of the commit

	*/
	Sha string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the repo list statuses params
func (o *RepoListStatusesParams) WithTimeout(timeout time.Duration) *RepoListStatusesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the repo list statuses params
func (o *RepoListStatusesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the repo list statuses params
func (o *RepoListStatusesParams) WithContext(ctx context.Context) *RepoListStatusesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the repo list statuses params
func (o *RepoListStatusesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the repo list statuses params
func (o *RepoListStatusesParams) WithHTTPClient(client *http.Client) *RepoListStatusesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the repo list statuses params
func (o *RepoListStatusesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOwner adds the owner to the repo list statuses params
func (o *RepoListStatusesParams) WithOwner(owner string) *RepoListStatusesParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the repo list statuses params
func (o *RepoListStatusesParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithRepo adds the repo to the repo list statuses params
func (o *RepoListStatusesParams) WithRepo(repo string) *RepoListStatusesParams {
	o.SetRepo(repo)
	return o
}

// SetRepo adds the repo to the repo list statuses params
func (o *RepoListStatusesParams) SetRepo(repo string) {
	o.Repo = repo
}

// WithSha adds the sha to the repo list statuses params
func (o *RepoListStatusesParams) WithSha(sha string) *RepoListStatusesParams {
	o.SetSha(sha)
	return o
}

// SetSha adds the sha to the repo list statuses params
func (o *RepoListStatusesParams) SetSha(sha string) {
	o.Sha = sha
}

// WriteToRequest writes these params to a swagger request
func (o *RepoListStatusesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param repo
	if err := r.SetPathParam("repo", o.Repo); err != nil {
		return err
	}

	// path param sha
	if err := r.SetPathParam("sha", o.Sha); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
