// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// RepoGetCombinedStatusByRefReader is a Reader for the RepoGetCombinedStatusByRef structure.
type RepoGetCombinedStatusByRefReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RepoGetCombinedStatusByRefReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRepoGetCombinedStatusByRefOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRepoGetCombinedStatusByRefOK creates a RepoGetCombinedStatusByRefOK with default headers values
func NewRepoGetCombinedStatusByRefOK() *RepoGetCombinedStatusByRefOK {
	return &RepoGetCombinedStatusByRefOK{}
}

/*RepoGetCombinedStatusByRefOK handles this case with default header values.

Status
*/
type RepoGetCombinedStatusByRefOK struct {
	Payload RepoGetCombinedStatusByRefOKBody
}

func (o *RepoGetCombinedStatusByRefOK) Error() string {
	return fmt.Sprintf("[GET /repos/{owner}/{repo}/commits/{ref}/statuses][%d] repoGetCombinedStatusByRefOK  %+v", 200, o.Payload)
}

func (o *RepoGetCombinedStatusByRefOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*RepoGetCombinedStatusByRefOKBody Status holds a single Status of a single Commit
swagger:model RepoGetCombinedStatusByRefOKBody
*/
type RepoGetCombinedStatusByRefOKBody struct {

	// context
	// Required: true
	Context *string `json:"context"`

	// created
	// Required: true
	// Format: date-time
	Created *strfmt.DateTime `json:"created_at"`

	// description
	// Required: true
	Description *string `json:"description"`

	// ID
	// Required: true
	ID *int64 `json:"id"`

	// target URL
	// Required: true
	TargetURL *string `json:"target_url"`

	// URL
	// Required: true
	URL *string `json:"url"`

	// updated
	// Required: true
	// Format: date-time
	Updated *strfmt.DateTime `json:"updated_at"`

	// creator
	// Required: true
	Creator *RepoGetCombinedStatusByRefOKBodyCreator `json:"creator"`

	// StatusState holds the state of a Status
	// It can be "pending", "success", "error", "failure", and "warning"
	// Required: true
	Status *string `json:"status"`
}

// Validate validates this repo get combined status by ref o k body
func (o *RepoGetCombinedStatusByRefOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateContext(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateCreated(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateDescription(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTargetURL(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUpdated(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateCreator(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RepoGetCombinedStatusByRefOKBody) validateContext(formats strfmt.Registry) error {

	if err := validate.Required("repoGetCombinedStatusByRefOK"+"."+"context", "body", o.Context); err != nil {
		return err
	}

	return nil
}

func (o *RepoGetCombinedStatusByRefOKBody) validateCreated(formats strfmt.Registry) error {

	if err := validate.Required("repoGetCombinedStatusByRefOK"+"."+"created_at", "body", o.Created); err != nil {
		return err
	}

	if err := validate.FormatOf("repoGetCombinedStatusByRefOK"+"."+"created_at", "body", "date-time", o.Created.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *RepoGetCombinedStatusByRefOKBody) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("repoGetCombinedStatusByRefOK"+"."+"description", "body", o.Description); err != nil {
		return err
	}

	return nil
}

func (o *RepoGetCombinedStatusByRefOKBody) validateID(formats strfmt.Registry) error {

	if err := validate.Required("repoGetCombinedStatusByRefOK"+"."+"id", "body", o.ID); err != nil {
		return err
	}

	return nil
}

func (o *RepoGetCombinedStatusByRefOKBody) validateTargetURL(formats strfmt.Registry) error {

	if err := validate.Required("repoGetCombinedStatusByRefOK"+"."+"target_url", "body", o.TargetURL); err != nil {
		return err
	}

	return nil
}

func (o *RepoGetCombinedStatusByRefOKBody) validateURL(formats strfmt.Registry) error {

	if err := validate.Required("repoGetCombinedStatusByRefOK"+"."+"url", "body", o.URL); err != nil {
		return err
	}

	return nil
}

func (o *RepoGetCombinedStatusByRefOKBody) validateUpdated(formats strfmt.Registry) error {

	if err := validate.Required("repoGetCombinedStatusByRefOK"+"."+"updated_at", "body", o.Updated); err != nil {
		return err
	}

	if err := validate.FormatOf("repoGetCombinedStatusByRefOK"+"."+"updated_at", "body", "date-time", o.Updated.String(), formats); err != nil {
		return err
	}

	return nil
}

func (o *RepoGetCombinedStatusByRefOKBody) validateCreator(formats strfmt.Registry) error {

	if err := validate.Required("repoGetCombinedStatusByRefOK"+"."+"creator", "body", o.Creator); err != nil {
		return err
	}

	if o.Creator != nil {
		if err := o.Creator.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("repoGetCombinedStatusByRefOK" + "." + "creator")
			}
			return err
		}
	}

	return nil
}

func (o *RepoGetCombinedStatusByRefOKBody) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("repoGetCombinedStatusByRefOK"+"."+"status", "body", o.Status); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *RepoGetCombinedStatusByRefOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RepoGetCombinedStatusByRefOKBody) UnmarshalBinary(b []byte) error {
	var res RepoGetCombinedStatusByRefOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*RepoGetCombinedStatusByRefOKBodyCreator User represents a user
swagger:model RepoGetCombinedStatusByRefOKBodyCreator
*/
type RepoGetCombinedStatusByRefOKBodyCreator struct {

	// URL to the user's avatar
	AvatarURL string `json:"avatar_url,omitempty"`

	// email
	// Format: email
	Email strfmt.Email `json:"email,omitempty"`

	// the user's full name
	FullName string `json:"full_name,omitempty"`

	// the user's id
	ID int64 `json:"id,omitempty"`

	// User locale
	Language string `json:"language,omitempty"`

	// the user's username
	UserName string `json:"login,omitempty"`
}

// Validate validates this repo get combined status by ref o k body creator
func (o *RepoGetCombinedStatusByRefOKBodyCreator) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RepoGetCombinedStatusByRefOKBodyCreator) validateEmail(formats strfmt.Registry) error {

	if swag.IsZero(o.Email) { // not required
		return nil
	}

	if err := validate.FormatOf("repoGetCombinedStatusByRefOK"+"."+"creator"+"."+"email", "body", "email", o.Email.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *RepoGetCombinedStatusByRefOKBodyCreator) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RepoGetCombinedStatusByRefOKBodyCreator) UnmarshalBinary(b []byte) error {
	var res RepoGetCombinedStatusByRefOKBodyCreator
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
